return {
	{ bundle = "a2bdefafc2bcdcf1", package = "content/fx/particles/weapons/foce_sword/forcesword_2h_special_low" },
	{ bundle = "3d574968047de622", package = "content/fx/particles/enemies/buff_burning" },
	{ bundle = "ec588082b617bc4d", package = "content/fx/particles/enemies/buff_burning_stack_lvl02" },
	{ bundle = "a9dfcc3f7330140a", package = "content/fx/particles/enemies/buff_burning_stack_lvl03" },
	{ bundle = "c0c865abfb9f366a", package = "content/fx/particles/weapons/rifles/plasma_gun/plasma_beam_linger" },
	{ bundle = "f6f1954051323147", package = "content/fx/particles/impacts/weapons/lasgun/lasgun_impact_player" },
	{ bundle = "689dc94618cb3a45", package = "content/fx/particles/impacts/weapons/lasgun/lasgun_impact_surface_player" },
	{ bundle = "038a622c4f8dae2c", package = "content/fx/particles/impacts/weapons/lasgun/lasgun_sparks_armor_player" },
	{ bundle = "f9a026d45df7bcea", package = "content/fx/particles/impacts/surfaces/impact_snow_laser_01" },
	{ bundle = "612e6312440e0738", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_beam_krieg_charged" },
	{ bundle = "09cba8bbfcd95fe1", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_beam_krieg_linger" },
	{ bundle = "4a23053559b62d82", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_beam_krieg_linger_bfg" },
	{ bundle = "d39791625c6317ee", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_bfg_muzzle" },
	{ bundle = "9a67cf5c0db091b7", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_bfg_muzzle_crit" },
	{ bundle = "348d27134018dd32", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_charged_muzzle" },
	{ bundle = "d753d8a1655a082f", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_charged_muzzle_crit" },
	{ bundle = "f038b72029cdfd17", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_crit_trail" },
	{ bundle = "5927ca5a6b4ab0af", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_chargeup_skull_yellow" },
	{ bundle = "ec4de4ad48cd9642", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_muzzle" },
	{ bundle = "07b2d9094a94893e", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_muzzle_crit" },
	{ bundle = "14a1118d1b478a79", package = "content/fx/particles/weapons/rifles/lasgun/lasgun_muzzle_elysian" },
	{ bundle = "e064bea4d1676af6", package = "content/fx/particles/weapons/rifles/laspistol/lasgun_heavy_beam_crit_trail" },
	{ bundle = "06c8bd5dcfb5e7eb", package = "content/fx/particles/weapons/rifles/laspistol/laspistol_heavy_muzzle" },
	{ bundle = "65fffac97bc7ff98", package = "content/fx/particles/weapons/rifles/laspistol/laspistol_heavy_muzzle_crit" },
	{ bundle = "0248bd48defd788e", package = "content/fx/particles/weapons/rifles/laspistol/laspistol_muzzle" },
}
